### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by Aemeath5** [Xtao-Team/GCAuth-OAuth#3]
![QQ图片20220519010634](https://user-images.githubusercontent.com/84051485/169104505-a8e155e3-5312-4f31-bd88-489c8b491af3.png)

**Comment by Becods** [comment]
[#usage](https://github.com/Xtao-Team/GCAuth-OAuth/tree/main#usage)

**Comment by Aemeath5** [comment]
I did follow the tutorial configuration but still couldn't launch the plug-in
![56b08cf615db4320](https://user-images.githubusercontent.com/84051485/169272447-aa8f3251-da99-4307-a7c9-0cfaccd02f38.png)
![-495bb73f9fe1ac2c](https://user-images.githubusercontent.com/84051485/169272464-95506f7a-81ee-49eb-acbd-3c4bbb92134d.png)
![-2e1f826d03f9f7a5](https://user-images.githubusercontent.com/84051485/169272471-e3cb1783-6512-4f30-ac5f-baa9cab1865f.png)

**Comment by Becods** [comment]
> Put the all the [frontend](https://github.com/Xtao-Team/GCAuth-OAuth/tree/main#Frontend) files into the folder GRASSCUTTER_RESOURCE/**plugins/GCAuth/OAuth**. Note that your must have login.html for now. You are free to put any other dynamiclly loaded file(e.g. .js, .css) in that folder. Check the last section for current available frontend.

![image.png](https://s2.loli.net/2022/05/19/fFdqIlwnh3J2D1x.png)

**plugins/GCAuth/OAuth**

**Comment by Aemeath5** [comment]
Thank you very much. It has been solved

**Comment by duohuanlei** [comment]
我需要自己生成jar包然后放置到plugins里创建一个GCAuth_OAuth的目录里么
