### ISSUE TITLE
help me please!!

### ISSUE THREAD

**Issue by JarvisQin** [Xtao-Team/GCAuth-OAuth#4]
![image](https://user-images.githubusercontent.com/35295796/170836044-7aa4b0b7-0b21-4524-a3fd-6ec12b7fc92f.png)
登录的时候显示500 status_code_5xx(500)

**Comment by JarvisQin** [comment]
![image](https://user-images.githubusercontent.com/35295796/170836548-1aa6a194-217f-4d31-b6b8-8a909812260d.png)

**Comment by Aemeath5** [comment]
你个人才用英语说，这个插件11天没更新了只有更新了才能解决

**Comment by omg-xtao** [comment]
updated to [v1.2.0](https://github.com/Xtao-Team/GCAuth-OAuth/releases/tag/v1.2.0)
